version: "3.7"
services:
    redis:
        image: redis:latest
        ports:
            - '6379:6379'
        expose:
        - "6379"
        # enable fully-durable alternative to snapshotting
        command: ["sh", "-c", "redis-server --appendonly yes --bind 0.0.0.0"]
    workers:
        image: workers
        build:
            context: .
            dockerfile: workers/Dockerfile
        volumes:
            - ./:/app
        links:
            - redis
        depends_on:
            - redis
    rq-dashboard:
        image: rq-dashboard
        build:
            context: .
            dockerfile: rq-dashboard/Dockerfile
        ports:
            - '9181:9181'
        expose:
            - "9181"
        links:
            - redis
        depends_on:
            - redis
